### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'watchRun' of undefined in  AllActivationGrids.html

### ISSUE THREAD

**Issue by dylan-wu** [distillpub/post--building-blocks#26]
I'm trying to run a dev repo.

My environment:

```bash
$ node --version
v9.3.0
$ npm --version
5.6.0
```

I see this in the browser. Note the page is working behind the error message.

![image](https://user-images.githubusercontent.com/6586811/42464259-270d7e6c-836e-11e8-95e9-5ceaf25b04dc.png)

Here is what I see in the terminal:

```
$ npm run dev

> saliency@ dev /Users/admin/temp/distil/post--building-blocks
> cross-env NODE_ENV=development webpack-dev-server --hot

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/admin/temp/distil/post--building-blocks/public
404s will fallback to /index.html
   574 modules

ERROR in ./src/diagrams/AllActivationGrids.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/Loading.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/ExamplePicker.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/Atoms.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/SemanticDict.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/StickyPicker.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/ActivationVecVis.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/ActivationGridSingle.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/Teaser.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/AttributionSpatial.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/AttributionChannel.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/ActivationGroups.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/Grammar.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/AttributionGroups.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/CubeGroups.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)

ERROR in ./src/diagrams/CubeNatural.html
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/Users/admin/temp/distil/post--building-blocks/node_modules/svelte-loader/index.js:83:46)
webpack: Failed to compile.

```

**Comment by ludwigschubert** [comment]
Looks like you're running into https://github.com/sveltejs/svelte-loader/issues/63. We may be able to fix by explicitly specifying an older version of svelte-loader.

**Comment by dylan-wu** [comment]
Thanks @ludwigschubert for pointing out sveltejs was the problem. The fix is to update sveltejs.
```bash
$ npm install -U svelte 
```
fixed it for me. My svelte is 1.64.1.

**Comment by anusharma9462** [comment]
I ma getting new error
10% building 2/2 modules 0 active(node:8476) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\dev\webprod-cap\app\build
i ｢wds｣: 404s will fallback to /index.html
